### PR TITLE
Add padding property to MarkdownWidget

### PR DESCRIPTION
**Pull request by jarekb123**
I wanted to have control on padding of under the hood scroll view

### CODE REVIEW

**Comment by asjqkkkk** [comment]
Hi,  add a padding attribute, you have no need to add a version description😂

**Comment by jarekb123** [comment]
Hmm. This is what CHANGELOG is used for. You made a version change, you write down what has changed.

**Comment by asjqkkkk** [comment]
> Hmm. This is what CHANGELOG is used for. You made a version change, you write down what has changed.

yes, it dose, the content of CHANGELOG is published by me after integration
but just adding a padding property is completely unnecessary to add a separate CHANGELOG😂

**Comment by asjqkkkk** [comment]
because there are a lots of properties between `ListView` and `ScrollablePositionedList`

**Comment by jarekb123** [comment]
Ok, I will revert that commit

niedz., 5 lip 2020, 12:30 użytkownik 安卓小哥 <notifications@github.com>
napisał:

**Pull request merged**
